ccf.py, ephys.py, experiment.py, lab.py
Need to add comments to tables and attributes
=> Schema designed jointly in MAP workshop on Friday 11/17

scripts/ingest.py
Added some sanity checks for trial start/end indexing times to prevent ingest failures.
Also reworked pipeline imports here.
=> scripts/ingest.py: better handle start/end index issues

pipeline/ingest/behavior.py, scripts/map-mock-data.py
issues outlined in TODO block, line 577:
```       #
#
#
#
#
#
```
=> [WIP] initial photostim ingest logic. 

pipeline/__init__.py, pipeline/ingest/behavior.py, pipeline/ingest/ephys.py
adjustments to bitcode loading paths, update for dj#511 inserts (`allow_direct_insert=True`)
this means running latest datajoint currently
=> bitcode branch: misc path fixups, fix for dj#511 inserts

pipeline/experiment.py, pipeline/ingest/behavior.py, pipeline/lab.py
Updates for photostim event schema restructuring & ingest adjustments
=> photostim updates

pipeline/ingest/ephys.py
This will not impact actual data loaded, since session-probe:bitcode file vs session-probe:ephys file is still 1:1 , however the intent of the ingest `EphysIngest.EphysFile` table was to track the core ephys files directly (and not the bitcode ones). 
Ideally, previously ingested sessions should be reloaded or this field manually corrected after the patch has been applied
=> pipeline/ingest/ephys.py: correct logged subpath from bitcode file to ephys file

pipeline/psth.py
utility function for easier retrieval of common plotting data; 
accompanying library psth plotting functions to follow as function is solidified
=> [WIP] pipeline/psth.py: add CellPsth.get() to retrieve per-unit psth plotting data

pipeline/ingest/tracking.py
per https://github.com/vathes/map-ephys/pull/154
=> handle multi-sess per day in .txt filename as well

notebook/data-visualization/foraging_inspector.ipynb, pipeline/plot/foraging_plot.py
Now Marton and Nai-Wen's Jupyter foraging inspector fully works in the main pipeline, rendering same plots as before.
=> make the foraging inspector work

pipeline/fixes/fix_0014_undo_bitvolt_scaling_for_unit_amp.py, pipeline/foraging_analysis.py, pipeline/ingest/behavior.py, pipeline/ingest/ephys.py, requirements.txt
Per @ttngu207 / https://github.com/vathes/map-ephys/pull/171 -
only scale non-curated ks sessions, add fix to undo scaling to those already loaded.
=>  unit_amp bitvolt scaling fix

pipeline/foraging_analysis.py, pipeline/report.py, pipeline/shell.py
per @ttngu207 in https://github.com/vathes/map-ephys/pull/173
=> add workers' populate routine for `analysis_foraging` and report generation

pipeline/publication.py, pipeline/shell.py, scripts/globus-shell.py
* add ks2 file types to pattern matches
* fixups for new paths
* retrieve1 now allows file-level filtering
=> publication update

doc/ingestion_instruction.md, pipeline/ingest/tracking.py
from @ttngu207 via https://github.com/vathes/map-ephys/pull/192
=> tracking ingest - handle file-searching ambiguity between camera: side vs. side_face

pipeline/ephys.py, pipeline/export.py, pipeline/ingest/ephys.py, pipeline/shell.py
from @ttngu207 via https://github.com/vathes/map-ephys/pull/193 and https://github.com/vathes/map-ephys/pull/194
=> add UnitNoiseLabel, UnitNote, MAPClusterMetric and computation implementation for MAP's drift QC metric

pipeline/ephys.py
via: https://github.com/mesoscale-activity-map/map-ephys/pull/195
=> pipeline/ephys.py: fix key_source join issue in UnitNote/UnitNoiseLabel

pipeline/ingest/behavior.py, pipeline/ingest/ephys.py, pipeline/lab.py, pipeline/plot/unit_psth.py, pipeline/psth.py, pipeline/psth_foraging.py, pipeline/shell.py, pipeline/util.py
1. behavior bitcode
2. ephys notes
3. more flexible ephys folder name
4. add new schema psth_foraging
5. add new plotting function in plot/unit_psth
=> foraging ephys ingestion

pipeline/ephys.py, pipeline/experiment.py, pipeline/ingest/behavior.py, pipeline/ingest/ephys.py, pipeline/ingest/util.py, pipeline/psth.py, pipeline/psth_foraging.py, pipeline/shell.py, pipeline/tracking.py, scripts/map-mock-data.py
from @ttngu207 via https://github.com/mesoscale-activity-map/map-ephys/pull/206
=> histology format 2 (IBL GUI) electrodes coords and probe tracks, multi-shank - RRig-MTL layout, matlab stubs 

pipeline/ephys.py, pipeline/ingest/util.py
Add a sanity check function for synchrony across devices
=> compare_ni_and_bpod_times

pipeline/plot/unit_psth.py, pipeline/psth_foraging.py, pipeline/util.py
1. added a new table `psth_foraging.AlignType` to define arbitrary temporal alignments
2. add `plot.unit_psth.plot_unit_psth_choice_outcome`
=> flexible PSTH for foraging task

notebook/data_export.ipynb, pipeline/ephys.py, pipeline/experiment.py, pipeline/ingest/ephys.py, pipeline/report.py, pipeline/shell.py, requirements.txt
* pull up to project (include foraging commits from han)
* include https://github.com/vathes/map-ephys/pull/211 via @ttngu207
=> pull-up from project, bugfixes from vathes 211

pipeline/report.py
Adding a new table to visualize Unit Level Foraging Repor.
=> Add UnitLevelForagingEphysReport

pipeline/ephys.py, pipeline/export/nwb.py, pipeline/histology.py, pipeline/ingest/ephys.py, pipeline/ingest/utils/spike_sorter_loader.py, requirements.txt, scripts/delay_response_NWB_export_Nov2022.py
- Minor bugfixes in NWB export
- Added raw data export in NWB export
- Added script to perform data upload to DANDI archive
=> minor improvement to ingest pykilosort - update NWB export (include raw data)
